# Generated by Django 5.1.6 on 2025-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('grape_type', models.CharField(max_length=255)),
                ('sugar', models.FloatField()),
                ('brix', models.FloatField()),
                ('ph', models.FloatField()),
                ('acidity', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('wine_style', models.CharField(max_length=50)),
            ],
        ),
    ]
