services:
  - type: web
    name: wine-fermentation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wine_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: wine_backend.settings
      - key: PYTHON_VERSION
        value: 3.11
